FROM python:3.10

WORKDIR /src

RUN pip install pipenv
RUN apt-get update && apt-get install -y netcat-openbsd

COPY . .

RUN pipenv install --system

CMD ["echo", "hello"]
RUN useradd appuser && chown -R appuser /src
USER appuser

RUN ["chmod", "+x", "/src/scheduler-entrypoint.sh"]

ENTRYPOINT ["sh", "/src/scheduler-entrypoint.sh"]